dist: jammy
language: rust
sudo: required
rust:
- stable
env:
  global:
  - CRATE_NAME=gcsf
  - secure: FPEA8LSJpjWzpQuLW1GvFkjzclnnrypwHxIEqDboO4KO/L1RzF5EJaODoXPTLRF0kXCzO0udosV27G7FPpP88IDFxA5RGlNSaDfmcLwX3A5W4i+4LZJOtT5nbpirx0mUj+3JuVWyOEX0dmyoCHfKjaYPNcEAGprfplJY7IInkzlovwaDmJjpPIG1lIp64S+yVQB1zhOGtYFjK9xUWcz1mTkrlLgJ39Tu+x8x5yuYSQZUZYOQ3NmV8wCwIpKcDxz5sBJttd2tvBmy8JiwYEZJ8CbMGJuPs7Dg7v1DkmzKb0DFAsDiMQ5uU/GQjfJgCOGWEebh9aaYovvPEJlV5AQnTRYg5qVh6/ZMxrF5k0SsikFr7B4Nec4XZBv0OrGXxIHN6khzWfRHN5dxmCBMKdOO36D0tlqk4ZAH+Up+LCN3gxQZoAl7NloAb8s3c/476Degu4SQVAW6Wf1us8PTCHgA1XhfYbOfg1EOm2900QMkM0zLfSMsI+hvNIrpDNMrzegboHbaGQnAlRKYLNYQ4AOyS0WQgjEPuan9+HwolLkJVvGwUA5Agzpq47xNdfZj7IL/10VgLaJspt1KxaTUxymq5e+JGGLE3lrdIbS8bSXOQ6Zjf3P0/7Oz3RSvGWHkXBjHdEOU3HBKi1htQKEAR2/T0rehqoBNo1TC+QIkPtl0lpQ=
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-apple-darwin
    os: osx
before_install:
- if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then brew update; brew install pkg-config;
  brew tap homebrew/cask; brew cask install osxfuse; fi
- if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then sudo apt-get -qq update; sudo apt-get
  install -y libfuse-dev pkg-config; fi
before_script:
- rustup self update
- rustup component add rustfmt-preview
script:
- cargo fmt --all -- --check
- cargo build
- cargo test
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: FPEA8LSJpjWzpQuLW1GvFkjzclnnrypwHxIEqDboO4KO/L1RzF5EJaODoXPTLRF0kXCzO0udosV27G7FPpP88IDFxA5RGlNSaDfmcLwX3A5W4i+4LZJOtT5nbpirx0mUj+3JuVWyOEX0dmyoCHfKjaYPNcEAGprfplJY7IInkzlovwaDmJjpPIG1lIp64S+yVQB1zhOGtYFjK9xUWcz1mTkrlLgJ39Tu+x8x5yuYSQZUZYOQ3NmV8wCwIpKcDxz5sBJttd2tvBmy8JiwYEZJ8CbMGJuPs7Dg7v1DkmzKb0DFAsDiMQ5uU/GQjfJgCOGWEebh9aaYovvPEJlV5AQnTRYg5qVh6/ZMxrF5k0SsikFr7B4Nec4XZBv0OrGXxIHN6khzWfRHN5dxmCBMKdOO36D0tlqk4ZAH+Up+LCN3gxQZoAl7NloAb8s3c/476Degu4SQVAW6Wf1us8PTCHgA1XhfYbOfg1EOm2900QMkM0zLfSMsI+hvNIrpDNMrzegboHbaGQnAlRKYLNYQ4AOyS0WQgjEPuan9+HwolLkJVvGwUA5Agzpq47xNdfZj7IL/10VgLaJspt1KxaTUxymq5e+JGGLE3lrdIbS8bSXOQ6Zjf3P0/7Oz3RSvGWHkXBjHdEOU3HBKi1htQKEAR2/T0rehqoBNo1TC+QIkPtl0lpQ=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    tags: true
  provider: releases
  cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
