[package]
name = "gcsf"
description = "Filesystem based on Google Drive"
version = "0.1.28"
repository = "https://github.com/harababurel/gcsf"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"
keywords = ["google", "drive", "fuse", "filesystem"]
exclude = ["build/**/*.o", "doc/**/*.html", "client_secret.json", "/ci/*"]
edition = "2021"


[dependencies]
chrono = "0.4.26"
clap = { version = "2.33.0", features = ["yaml"] }
config = "0.13.3"
ctrlc = "3.4.0"
failure = "0.1.8"
fuser = "0.12"
# google-drive3 = "1.0.7+20171201"
google-drive3-fork = "1.0.10"
id_tree = "1.8.0"
lazy_static = "1.4.0"
libc = "0.2.147"
log = "0.4.19"
lru_time_cache = "0.11.11"
maplit = "1.0.2"
mime-sniffer = "0.1.2"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
serde = "1.0.174"
serde_derive = "1.0.174"
serde_json = "1.0.103"
time = "0.1"
xdg = "2.5.2"
yup-oauth2 = "1"

# These versions required by google-drive3
hyper = "0.10"
hyper-native-tls = "0.3.0"
